image: docker:latest

services:
- docker:dind

variables:
  DOCKER_DRIVER: overlay2
  IMAGE_NAME: $DOCKER_HUB_USERNAME/mon-api
  COMMIT_TAG: $CI_COMMIT_SHORT_SHA

stages:
- build
- push

before_script:
- echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin

build:
  stage: build
  script:
  - docker build -t $IMAGE_NAME:$COMMIT_TAG .
  - docker tag $IMAGE_NAME:$COMMIT_TAG $IMAGE_NAME:latest

push:
  stage: push
  script:
  - docker push $IMAGE_NAME:$COMMIT_TAG
  - docker push $IMAGE_NAME:latest
